const mongoose = require("mongoose");

const ModelSchema = new mongoose.Schema(
  {
    uuid: { type: String },
    email: { type: String },
    fullName: { type: String },
    isFeatured: { type: Boolean, default: true },
    isVerified: { type: Boolean, default: false },
    agency: { type: String },
    photos: { type: Array },
    polaroids: { type: Array },
    compCard: { type: String },
    videos: { type: Array },
    picture: { type: String },
    country: { type: String },
    state: { type: String },
    shortDesc: { type: String },
    category: { type: Array },
    followers: { type: Array },
    followings: { type: Array },
    instagram: { type: String },
    twitter: { type: String },
    facebook: { type: String },
    bio: { type: String },
    height: { type: String },
    waist: { type: String },
    chest: { type: String },
    shoulder: { type: String },
    hip: { type: String },
    shoe: { type: String },
    hairColor: { type: String },
    skinColor: { type: String },
    waist: { type: String },
    eyes: { type: String },
    tattoos: { type: Boolean },
    hairLength: { type: String },
    language: { type: String },
    bust: { type: String },
    size: { type: String },
    gender: { type: String },
    ethnicity: { type: String },
    availableForTravel: { type: Boolean },
    interestedJob: { type: Array },
    wallet: { type: Number, default: 0 },
    total: { type: Number, default: 0 },
    pending: { type: Number, default: 0 },
    withdrawn: { type: Number, default: 0 },
    minPrice: { type: Number, default: 0 },
    maxPrice: { type: Number, default: 0 },
    visitors: { type: Number, default: 0 },
    acceptedJobs: { type: Array },
    rejectedJobs: { type: Array },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Model", ModelSchema);
